// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CheckItem struct {
	Sku  string `json:"SKU"`
	Name string `json:"Name"`
	Qty  int    `json:"Qty"`
}

type CheckoutItem struct {
	Items []*CheckItem `json:"items"`
	Price float64      `json:"Price"`
}

type InputItem struct {
	Sku  *string `json:"SKU"`
	Name string  `json:"Name"`
	Qty  int     `json:"Qty"`
}

type Item struct {
	Sku   string  `json:"SKU"`
	Name  string  `json:"Name"`
	Price float64 `json:"Price"`
	Qty   int     `json:"Qty"`
}
