#!/usr/bin/env bash
# Usage: script/gocover
#
# coverage test

set -e 
go test ./... -covermode=count -coverprofile=cover.out
go test ./... -json > test-report.out
go tool cover -func=cover.out
$HOME/gopath/bin/goveralls -coverprofile=cover.out -service=travis-ci